#!/usr/bin/env node
/**
 * Nocturne release audit
 *
 * Dependency-free source/installed package checks. Source mode understands that
 * procedural WAV beds are generated by install.py; installed mode requires them.
 * Hard asset checks are derived from the canonical manifest's `src` fields—not
 * provenance filenames or narrative documentation.
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, extname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { resolveCatalogPath } from "./path_safety.mjs";

let root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
let installedMode = false;
let sourceMode = false;
let reportArgument = null;
const rawArgs = process.argv.slice(2);
for (let index = 0; index < rawArgs.length; index += 1) {
  const arg = rawArgs[index];
  if (arg === "--installed") installedMode = true;
  else if (arg === "--source") sourceMode = true;
  else if (arg === "--report" || arg === "--root") {
    const value = rawArgs[index + 1];
    if (!value) {
      console.error(`${arg} requires a path`);
      process.exit(2);
    }
    index += 1;
    if (arg === "--report") reportArgument = value;
    else root = resolve(value);
  } else {
    console.error(`Unknown argument: ${arg}`);
    process.exit(2);
  }
}
if (installedMode && sourceMode) {
  console.error("Choose either --source or --installed, not both.");
  process.exit(2);
}
const mode = installedMode ? "installed" : "source";
const ignoredDirs = new Set(["node_modules", ".git", ".venv", "dist", "build", ".next", "coverage", ".cache", "__pycache__", "verification-artifacts", "verification-logs", "review_bundles"]);
const ignoredFiles = new Set([
  "release-audit.json",
  "IMPLEMENTATION_REPORT.md",
  "VERIFICATION_REPORT.md",
  "CHANGE_SUMMARY.md",
  "NOCTURNE_ALPHA13_HARDENING.patch",
]);
const audioExt = new Set([".mp3", ".wav", ".ogg", ".m4a", ".aac", ".flac", ".opus", ".webm"]);
const errors = [];
const warnings = [];
const passes = [];

function rel(path) {
  return relative(root, path).split(sep).join("/");
}

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    if (ignoredDirs.has(name) || ignoredFiles.has(name)) continue;
    const path = join(dir, name);
    const stat = statSync(path);
    if (stat.isDirectory()) out.push(...walk(path));
    else out.push(path);
  }
  return out;
}

function readJson(path, label) {
  try {
    const value = JSON.parse(readFileSync(path, "utf8"));
    if (!value || Array.isArray(value) || typeof value !== "object") throw new Error("expected an object");
    return value;
  } catch (error) {
    errors.push(`${label} is invalid JSON: ${error.message}`);
    return {};
  }
}

function sha256(path) {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

function resolvePublicPath(src) {
  try {
    if (src.startsWith("/sounds/")) {
      return resolveCatalogPath(root, src.slice(1), join(root, "sounds"), `public sound path ${src}`);
    }
    if (src.startsWith("/")) {
      return resolveCatalogPath(root, `static/${src.slice(1)}`, join(root, "static"), `public static path ${src}`);
    }
  } catch (error) {
    errors.push(error.message);
  }
  return null;
}

function resolveInboxPath(value, label) {
  try {
    return resolveCatalogPath(root, value, join(root, "sounds", "inbox"), label);
  } catch (error) {
    errors.push(error.message);
    return null;
  }
}

function extractGeneratedJson(text, begin, end, label) {
  const start = text.indexOf(begin);
  const stop = text.indexOf(end);
  if (start < 0 || stop < 0 || stop <= start) {
    errors.push(`Missing generated ${label} markers in static/index.html.`);
    return {};
  }
  const raw = text.slice(start + begin.length, stop).trim();
  try {
    return JSON.parse(raw);
  } catch (error) {
    errors.push(`Generated ${label} fallback is invalid JSON: ${error.message}`);
    return {};
  }
}

function equalJson(a, b) {
  return JSON.stringify(a) === JSON.stringify(b);
}

const allFiles = walk(root);
const audioFiles = allFiles.filter((path) => audioExt.has(extname(path).toLowerCase()));
const inboxGuides = [
  "sounds/inbox/README.md",
  "sounds/inbox/quarantine-seam-risk/README.md",
  "sounds/inbox/quarantine-unverified/README.md",
  "sounds/inbox/seam-baked/README.md",
];
const missingInboxGuides = inboxGuides.filter((path) => {
  const absolute = join(root, path);
  return !existsSync(absolute) || statSync(absolute).size === 0;
});
if (missingInboxGuides.length) errors.push(`Missing or empty inbox documentation: ${missingInboxGuides.join(", ")}`);
else passes.push("All inbox and quarantine boundary guides are present and non-empty.");
for (const path of audioFiles) {
  if (statSync(path).size === 0) errors.push(`Empty audio asset: ${rel(path)}`);
}
if (audioFiles.length) {
  const hasQuarantineAudio = audioFiles.some((path) => rel(path).startsWith("sounds/inbox/"));
  passes.push(`${audioFiles.length} packaged audio assets are non-empty${hasQuarantineAudio ? " (including quarantine evidence)" : ""}.`);
} else errors.push("No packaged audio assets were found.");

// Exact duplicate payloads are usually accidental bloat; warn rather than fail.
const byHash = new Map();
for (const path of audioFiles) {
  const hash = sha256(path);
  const group = byHash.get(hash) ?? [];
  group.push(rel(path));
  byHash.set(hash, group);
}
for (const group of byHash.values()) {
  if (group.length > 1) warnings.push(`Byte-identical audio assets: ${group.join(", ")}`);
}

const manifestPath = join(root, "sounds", "sound_library.json");
const manifest = readJson(manifestPath, "sounds/sound_library.json");
const sounds = Array.isArray(manifest.sounds) ? manifest.sounds : [];
const defaults = Array.isArray(manifest.default_slots) ? manifest.default_slots : [];
const excluded = Array.isArray(manifest.excluded_sounds) ? manifest.excluded_sounds : [];
const releaseManifestPath = join(root, "RELEASE_MANIFEST.json");
const releaseManifest = existsSync(releaseManifestPath) ? readJson(releaseManifestPath, "RELEASE_MANIFEST.json") : {};
const profilePointerPath = join(root, "nocturne_profile.json");
const profilePointer = existsSync(profilePointerPath) ? readJson(profilePointerPath, "nocturne_profile.json") : { profile: "nocturne" };
const activeProfileId = ["nocturne", "nocturne-pi"].includes(profilePointer.profile) ? profilePointer.profile : "nocturne";
const activeProfilePath = join(root, "profiles", `${activeProfileId}.json`);
const activeProfile = existsSync(activeProfilePath) ? readJson(activeProfilePath, `profiles/${activeProfileId}.json`) : {};
const rainVideoEnabled = activeProfile?.visuals?.rain_video !== false;
for (const profileId of ["nocturne", "nocturne-pi"]) {
  const path = join(root, "profiles", `${profileId}.json`);
  if (!existsSync(path)) errors.push(`Profile definition is missing: profiles/${profileId}.json`);
  else {
    const profile = readJson(path, `profiles/${profileId}.json`);
    if (profile.id !== profileId) errors.push(`Profile file identity does not match ${profileId}.`);
  }
}
const detachedEvidence = new Map(
  (Array.isArray(releaseManifest.detached_evidence) ? releaseManifest.detached_evidence : [])
    .map((record) => [String(record?.path ?? ""), record])
    .filter(([path]) => path)
);
function validateDetachedRecord(path, expectedHash, expectedSize, label) {
  const record = detachedEvidence.get(path);
  if (!record) {
    errors.push(`Detached evidence record is missing for ${label}: ${path}`);
    return false;
  }
  if (expectedHash && record.sha256 !== expectedHash) errors.push(`Detached evidence hash metadata differs for ${label}: ${path}`);
  if (expectedSize != null && Number(record.size_bytes) !== Number(expectedSize)) errors.push(`Detached evidence size metadata differs for ${label}: ${path}`);
  return true;
}
if (!sounds.length) errors.push("Canonical manifest has no sounds[].");
if (defaults.length !== 8) errors.push(`default_slots must contain exactly 8 IDs; found ${defaults.length}.`);
if (new Set(defaults).size !== defaults.length) errors.push("default_slots contains duplicate IDs.");

const ids = new Set();
const srcs = new Set();
const byId = new Map();
const bySrc = new Map();
const generatorText = readFileSync(join(root, "scripts", "generate_noise.py"), "utf8");
let bundledCount = 0;
let generatedCount = 0;
let expectedGeneratedMissing = 0;
for (const raw of sounds) {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    errors.push("Manifest sounds[] contains a non-object entry.");
    continue;
  }
  const id = String(raw.id ?? "");
  const src = String(raw.src ?? "");
  const status = String(raw.status ?? "");
  const availability = String(raw.availability ?? "");
  if (!id) errors.push("Manifest sound is missing id.");
  else if (ids.has(id)) errors.push(`Duplicate sound id: ${id}`);
  else ids.add(id);
  if (!src.startsWith("/sounds/")) errors.push(`Sound ${id || "<unknown>"} has non-public src: ${JSON.stringify(src)}`);
  if (srcs.has(src)) errors.push(`Duplicate sound src: ${src}`);
  else if (src) srcs.add(src);
  if (!["core", "optional", "experimental"].includes(status)) errors.push(`Sound ${id} has invalid status: ${status}`);
  if (!["bundled", "install_generated"].includes(availability)) errors.push(`Sound ${id} has invalid availability: ${availability}`);
  if (status === "experimental" && (raw.recommended === true || defaults.includes(id))) {
    errors.push(`Experimental sound ${id} may not be recommended or default.`);
  }
  byId.set(id, raw);
  bySrc.set(src, raw);

  const path = resolvePublicPath(src);
  if (availability === "bundled") {
    bundledCount += 1;
    if (!path || !existsSync(path)) {
      errors.push(`Bundled sound ${id} is missing: ${src}`);
      continue;
    }
    const size = statSync(path).size;
    if (size === 0) errors.push(`Bundled sound ${id} is empty: ${src}`);
    if (Number(raw.file_size_bytes) !== size) errors.push(`Bundled sound ${id} size metadata is stale (${raw.file_size_bytes} != ${size}).`);
    const actualHash = sha256(path);
    if (raw.sha256 && raw.sha256 !== actualHash) errors.push(`Bundled sound ${id} SHA-256 does not match ${src}.`);
    if (raw.source_type === "recorded_cc0") {
      for (const field of ["source_url", "license", "sha256", "screenshot"]) {
        if (!raw[field]) errors.push(`Bundled recorded sound ${id} is missing provenance field ${field}.`);
      }
    }
  } else if (availability === "install_generated") {
    generatedCount += 1;
    const filename = src.split("/").pop() ?? "";
    if (!generatorText.includes(filename)) errors.push(`Generated manifest entry ${id} is not named in scripts/generate_noise.py (${filename}).`);
    if (path && existsSync(path)) {
      if (statSync(path).size <= 44) errors.push(`Generated sound ${id} is too small to be a valid WAV: ${src}`);
    } else if (installedMode) {
      errors.push(`Installed-mode generated sound is missing: ${src}`);
    } else {
      expectedGeneratedMissing += 1;
    }
  }
}

for (const id of defaults) {
  const sound = byId.get(id);
  if (!sound) {
    errors.push(`Default slot references unknown sound id: ${id}`);
    continue;
  }
  if (sound.status !== "core" || sound.recommended !== true) errors.push(`Default sound ${id} must be status=core and recommended=true.`);
  if (sound.availability !== "bundled") errors.push(`Default sound ${id} must be bundled for a complete first-run source package.`);
  const path = resolvePublicPath(String(sound.src ?? ""));
  if (!path || !existsSync(path)) errors.push(`Default sound ${id} file is missing: ${sound.src}`);
}
if (defaults.includes("waves-on-shore")) errors.push("Waves remains in default_slots despite the current Tonight curation decision.");
else passes.push("Waves remains optional but is not a Tonight default.");

const excludedIds = new Set();
for (const item of excluded) {
  const id = String(item?.id ?? "");
  if (!id) errors.push("excluded_sounds contains an entry without id.");
  if (excludedIds.has(id)) errors.push(`Duplicate excluded sound id: ${id}`);
  excludedIds.add(id);
  if (ids.has(id) || defaults.includes(id)) errors.push(`Quarantined sound ${id} leaked into the public catalog/defaults.`);
  if (item?.status !== "quarantined" || item?.public !== false) errors.push(`Excluded sound ${id} must declare status=quarantined and public=false.`);
  const detached = item?.retention === "evidence_bundle";
  if (item?.retention && !detached) errors.push(`Unknown retention profile for ${id}: ${item.retention}`);
  if (item?.quarantine_path) {
    const q = String(item.quarantine_path);
    const path = resolveInboxPath(q, `quarantine path for ${id}`);
    if (!path) continue;
    if (!existsSync(path)) {
      if (detached && validateDetachedRecord(q, item.sha256, item.file_size_bytes, id)) {
        passes.push(`${id} payload is intentionally detached to the companion evidence bundle.`);
      } else if (!detached) {
        errors.push(`Quarantine evidence for ${id} is missing: ${q}`);
      }
    } else {
      if (Number(item.file_size_bytes) !== statSync(path).size) errors.push(`Quarantine size metadata is stale for ${id}.`);
      if (item.sha256 && item.sha256 !== sha256(path)) errors.push(`Quarantine SHA-256 mismatch for ${id}.`);
    }
  }
  if (item?.transform_sidecar) {
    const sidecarRel = String(item.transform_sidecar);
    const sidecarPath = resolveInboxPath(sidecarRel, `transform sidecar for ${id}`);
    if (!sidecarPath) continue;
    if (!existsSync(sidecarPath)) {
      if (detached && validateDetachedRecord(
        sidecarRel,
        item.transform_sidecar_sha256,
        item.transform_sidecar_size_bytes,
        `${id} transform sidecar`,
      )) passes.push(`${id} transform sidecar is intentionally detached to the companion evidence bundle.`);
      else if (!detached) errors.push(`Transform sidecar for ${id} is missing: ${sidecarRel}`);
    } else {
      if (item.transform_sidecar_sha256 && item.transform_sidecar_sha256 !== sha256(sidecarPath)) errors.push(`Transform sidecar hash metadata is stale for ${id}.`);
      if (item.transform_sidecar_size_bytes != null && Number(item.transform_sidecar_size_bytes) !== statSync(sidecarPath).size) errors.push(`Transform sidecar size metadata is stale for ${id}.`);
      const sidecar = readJson(sidecarPath, `transform sidecar for ${id}`);
      if (sidecar.status !== "audition_required") errors.push(`Transform sidecar for ${id} must remain audition_required.`);
      if (sidecar.output?.sha256 !== item.sha256) errors.push(`Transform sidecar output hash differs from excluded_sounds for ${id}.`);
      if (!String(sidecar.claim_boundary ?? "").toLowerCase().includes("human audition")) errors.push(`Transform sidecar for ${id} lacks the human-audition claim boundary.`);
    }
  }
}
if (!excludedIds.has("rain-inside-house")) errors.push("Confirmed seam-risk rain is not recorded in excluded_sounds.");
if (!excludedIds.has("rain-inside-house-seam-baked")) errors.push("Seam-baked repair candidate is not recorded in excluded_sounds.");

const indexPath = join(root, "static", "index.html");
const dashboardPath = join(root, "static", "dashboard.html");
const polishPath = join(root, "static", "nocturne-polish.css");
const webManifestPath = join(root, "static", "manifest.webmanifest");
const rainVideoPath = join(root, "static", "rain.mp4");
const deviceMatrixPath = join(root, "docs", "DEVICE_TEST_MATRIX.md");
const mainText = readFileSync(join(root, "main.py"), "utf8");
const indexText = readFileSync(indexPath, "utf8");
const dashboardText = readFileSync(dashboardPath, "utf8");
const polishText = existsSync(polishPath) ? readFileSync(polishPath, "utf8") : "";
const embeddedManifest = extractGeneratedJson(
  indexText,
  "/* NOCTURNE:BEGIN GENERATED SOUND LIBRARY */",
  "/* NOCTURNE:END GENERATED SOUND LIBRARY */",
  "sound-library",
);
if (equalJson(manifest, embeddedManifest)) passes.push("Browser fallback exactly matches the canonical sound manifest.");
else errors.push("Browser fallback differs from sounds/sound_library.json; run python scripts/sync_release_data.py.");

const buildPath = join(root, "nocturne_build.json");
const build = readJson(buildPath, "nocturne_build.json");
const embeddedBuild = extractGeneratedJson(
  indexText,
  "/* NOCTURNE:BEGIN GENERATED BUILD INFO */",
  "/* NOCTURNE:END GENERATED BUILD INFO */",
  "build-info",
);
if (equalJson(build, embeddedBuild)) passes.push("Browser build fallback exactly matches nocturne_build.json.");
else errors.push("Browser build fallback differs from nocturne_build.json; run python scripts/sync_release_data.py.");

for (const field of ["version", "channel", "build_date_utc", "revision", "revision_kind", "source_date_utc", "feedback_label"]) {
  if (!build[field] || String(build[field]).includes("unknown")) errors.push(`Build identity is missing a concrete ${field}.`);
}
const feedbackLabel = String(build.feedback_label ?? "");
for (const name of ["README.md", "ALPHA_FEEDBACK.md"]) {
  const text = readFileSync(join(root, name), "utf8");
  if (!text.includes(feedbackLabel)) errors.push(`${name} does not contain the canonical feedback label.`);
  const versions = text.match(/v?0\.1\.0-alpha\.\d+(?:-[A-Za-z0-9.-]+)?/g) ?? [];
  for (const found of versions) {
    if (found.replace(/^v/, "") !== build.version) errors.push(`${name} contains stale release identity ${found}.`);
  }
}

const activeReleaseTexts = [
  ["README.md", readFileSync(join(root, "README.md"), "utf8")],
  ["ALPHA_FEEDBACK.md", readFileSync(join(root, "ALPHA_FEEDBACK.md"), "utf8")],
  ["sounds/sound_library.json notes", String(manifest.notes ?? "")],
  ["scripts/README.md", readFileSync(join(root, "scripts", "README.md"), "utf8")],
  ["scripts/make_dual_release.py", readFileSync(join(root, "scripts", "make_dual_release.py"), "utf8")],
  ["static/index.html rain-video cache key", indexText.match(/rain\.mp4\?v=([^"']+)/)?.[1] ?? ""],
];
const currentAlpha = String(build.version ?? "").match(/alpha\.(\d+)/i)?.[1];
if (!currentAlpha) {
  errors.push("Canonical build version does not contain an alpha sequence number.");
} else {
  for (const [name, text] of activeReleaseTexts) {
    for (const match of text.matchAll(/alpha(?:\.|[ _-])?(\d+)/gi)) {
      if (match[1] !== currentAlpha) {
        errors.push(`${name} contains stale active alpha reference ${match[0]}; current build is alpha.${currentAlpha}.`);
      }
    }
  }
  if (!errors.some((message) => message.includes("stale active alpha reference"))) {
    passes.push("Active release surfaces contain no stale numbered alpha references.");
  }
}

if (!existsSync(polishPath)) errors.push("Served polish stylesheet is missing: static/nocturne-polish.css");
for (const [name, text] of [["static/index.html", indexText], ["static/dashboard.html", dashboardText]]) {
  if (!/href=["']\/nocturne-polish\.css["']/.test(text)) errors.push(`${name} does not load /nocturne-polish.css.`);
}
for (const [name, text] of [["static/index.html", indexText], ["static/dashboard.html", dashboardText], ["static/nocturne-polish.css", polishText]]) {
  if (/outline\s*:\s*none/i.test(text)) errors.push(`${name} still suppresses focus outlines with outline:none.`);
}
if (!/:focus-visible/i.test(polishText)) errors.push("Polish stylesheet has no :focus-visible treatment.");
if (!/prefers-reduced-motion/i.test(polishText)) errors.push("Polish stylesheet has no reduced-motion treatment.");
if (!/forced-colors/i.test(polishText)) errors.push("Polish stylesheet has no forced-colors treatment.");
if (!/min-block-size:\s*44px/i.test(polishText)) errors.push("Polish stylesheet has no 44px coarse-pointer target safeguard.");

if (!existsSync(webManifestPath)) {
  errors.push("PWA manifest is missing: static/manifest.webmanifest");
} else {
  const webManifest = readJson(webManifestPath, "static/manifest.webmanifest");
  const expectedShortName = activeProfileId === "nocturne-pi" ? "Nocturne Pi" : "Nocturne";
  if (webManifest.short_name !== expectedShortName || webManifest.start_url !== "/" || webManifest.display !== "standalone") {
    errors.push(`PWA manifest does not carry the expected ${expectedShortName} install identity.`);
  }
  const icons = Array.isArray(webManifest.icons) ? webManifest.icons : [];
  for (const icon of icons) {
    const path = resolvePublicPath(String(icon?.src ?? ""));
    if (!path || !existsSync(path) || statSync(path).size === 0) errors.push(`Manifest icon is missing: ${icon?.src}`);
  }
  if (icons.length < 3) errors.push("PWA manifest should include 192 px, 512 px, and maskable icon records.");
}
if (!/rel=["']manifest["'][^>]+href=["']\/manifest\.webmanifest["']|href=["']\/manifest\.webmanifest["'][^>]+rel=["']manifest["']/i.test(indexText)) {
  errors.push("static/index.html does not link /manifest.webmanifest.");
}
const rainStillPath = join(root, "static", "rain-still.webp");
if (!existsSync(rainStillPath) || statSync(rainStillPath).size === 0) errors.push("Pi-compatible rain still is missing.");
if (rainVideoEnabled) {
  if (!existsSync(rainVideoPath) || statSync(rainVideoPath).size === 0) errors.push("Full profile rain video is missing.");
  else if (statSync(rainVideoPath).size >= 4_000_000) errors.push(`Rain video remains unexpectedly large (${statSync(rainVideoPath).size} bytes).`);
} else if (existsSync(rainVideoPath)) {
  warnings.push("Nocturne Pi package still contains the disabled rain video.");
}
if (/<source\s+src=["']\/rain\.mp4/i.test(indexText)) errors.push("Main HTML eagerly requests rain.mp4 before profile resolution.");
if (!/data-full-src=["']\/rain\.mp4/i.test(indexText)) errors.push("Main HTML lacks deferred full-profile video metadata.");
const provenanceText = readFileSync(join(root, "AUDIO_PROVENANCE.md"), "utf8");
const readmeText = readFileSync(join(root, "README.md"), "utf8");
if (!provenanceText.includes("retained/media/rain-transform.json") || !readmeText.includes("retained/media/rain-transform.json")) {
  errors.push("Product documentation does not point to the detached rain-video transform record.");
}
if (!existsSync(deviceMatrixPath)) {
  errors.push("Device integration results template is missing: docs/DEVICE_TEST_MATRIX.md");
} else {
  const matrixText = readFileSync(deviceMatrixPath, "utf8");
  if (!/status:\s*pending/i.test(matrixText) || !/plain LAN HTTP/i.test(matrixText) || !/trusted HTTPS/i.test(matrixText)) {
    errors.push("Device test matrix does not preserve the pending and launch-context boundaries.");
  }
}

const launcherText = readFileSync(join(root, "run_nocturne.py"), "utf8");
if (!launcherText.includes("--profile") || !mainText.includes('/api/profile')) errors.push("Shared-source profile selection is not exposed by launcher and API.");
if (!launcherText.includes("--ssl-certfile") || !launcherText.includes("--ssl-keyfile")) errors.push("Launcher lacks optional TLS certificate arguments.");
if (!mainText.includes("NOCTURNE_SCHEME")) errors.push("Ready URL does not track HTTP versus HTTPS launch mode.");
const loopBakerPath = join(root, "scripts", "bake_seamless_loop.py");
if (!existsSync(loopBakerPath)) errors.push("Offline seamless-loop baker is missing.");
else {
  const loopBakerText = readFileSync(loopBakerPath, "utf8");
  for (const signal of ["audition_required", "equal-power", "--allow-public-path", "sha256"]) {
    if (!loopBakerText.includes(signal)) errors.push(`Loop baker lacks safety/provenance signal: ${signal}`);
  }
}

// Runtime /sounds references are checked against manifest availability. Bare
// provenance filenames are intentionally not treated as executable references.
const runtimeSoundRefs = new Set();
const runtimePattern = /["'`](\/sounds\/[^"'`\n]+\.(?:mp3|wav|ogg|m4a|aac|flac|opus|webm))(?:\?[^"'`]*)?["'`]/gi;
for (const text of [indexText, dashboardText]) {
  for (const match of text.matchAll(runtimePattern)) runtimeSoundRefs.add(match[1]);
}
for (const ref of runtimeSoundRefs) {
  const entry = bySrc.get(ref);
  const path = resolvePublicPath(ref);
  if (path && existsSync(path)) continue;
  if (!installedMode && entry?.availability === "install_generated") continue;
  errors.push(`Missing runtime sound reference: ${ref}`);
}

if (!/first_part\[0\]\.casefold\(\)\s*==\s*["']inbox["']/.test(mainText)) errors.push("main.py does not visibly deny case variants of the sounds/inbox subtree.");
else passes.push("The public sound route denies the complete sounds/inbox quarantine tree.");

// Parse inline scripts for JavaScript syntax without executing browser behavior.
for (const [index, match] of [...indexText.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].entries()) {
  const code = match[1];
  if (!code.trim()) continue;
  try {
    // eslint-disable-next-line no-new-func
    new Function(code);
  } catch (error) {
    errors.push(`Inline JavaScript block ${index + 1} has a syntax error: ${error.message}`);
  }
}

const signals = [
  ["Silence / Resume states", /\bSilence\b[\s\S]*\bResume\b/i.test(indexText)],
  ["accessible pressed state", /aria-pressed/i.test(indexText)],
  ["Tonight picker hierarchy", /CATEGORY_TONIGHT[\s\S]*recommended/i.test(indexText)],
  ["explicit Experimental filter", /CATEGORY_EXPERIMENTAL[\s\S]*experimental/i.test(indexText)],
  ["sound-picker focus return", /pickerReturnFocus[\s\S]*\.focus\(\)/i.test(indexText)],
  ["schema-versioned local scenes", /SCENE_SCHEMA\s*=\s*1[\s\S]*schema:\s*SCENE_SCHEMA[\s\S]*MAX_SCENE_STORAGE_BYTES/i.test(indexText)],
  ["local named scenes", /SCENES_KEY[\s\S]*captureCurrentScene[\s\S]*applyLocalScene/i.test(indexText)],
  ["Media Session handlers", /mediaSession[\s\S]*setActionHandler/i.test(indexText)],
  ["background return check", /visibilitychange[\s\S]*inspectPlaybackAfterReturn/i.test(indexText)],
  ["honest browser alarm boundary", /not an alarm clock/i.test(indexText)],
];
for (const [label, present] of signals) {
  if (present) passes.push(`${label} is represented in active source.`);
  else errors.push(`Missing required static interaction signal: ${label}.`);
}

if (expectedGeneratedMissing && !installedMode) {
  passes.push(`${expectedGeneratedMissing} procedural WAV paths are correctly treated as install-generated in source mode.`);
}
passes.push(`${defaults.length} Tonight defaults are bundled; ${bundledCount} public bundled sounds and ${generatedCount} install-generated entries were checked.`);

const uniqueErrors = [...new Set(errors)];
const uniqueWarnings = [...new Set(warnings)];
const report = {
  schema: "nocturne.release-audit.v2",
  generatedAt: new Date().toISOString(),
  mode,
  overall: uniqueErrors.length ? "FAIL" : "PASS",
  counts: {
    files: allFiles.length,
    packagedAudioFiles: audioFiles.length,
    publicSounds: sounds.length,
    defaultSounds: defaults.length,
    excludedSounds: excluded.length,
    errors: uniqueErrors.length,
    warnings: uniqueWarnings.length,
  },
  passes,
  warnings: uniqueWarnings,
  errors: uniqueErrors,
  humanChecksRequired: [
    "Audition every Tonight/default sound on headphones, a phone/tablet speaker, and the intended bedside speaker.",
    "Record loop seams, unexpected events, fatigue, level jumps, and one mixed timer/fade session.",
    "Exercise keyboard and screen-reader behavior in a real browser; static tokens do not prove a usable experience.",
    "Run a real phone background/lock/unlock cycle and record the exact browser/launch context in docs/DEVICE_TEST_MATRIX.md; API presence does not prove OS survival.",
    "Audition the seam-baked candidate repeatedly before moving it out of sounds/inbox/.",
  ],
};
if (reportArgument) {
  const reportPath = isAbsolute(reportArgument) ? reportArgument : resolve(root, reportArgument);
  mkdirSync(dirname(reportPath), { recursive: true });
  writeFileSync(reportPath, `${JSON.stringify(report, null, 2)}\n`);
}
console.log(JSON.stringify(report, null, 2));
if (uniqueErrors.length) process.exitCode = 1;
