#!/usr/bin/env python3
"""Generate Nocturne audio credit and provenance documents from the manifest."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _manifest(root: Path) -> dict[str, Any]:
    path = root / "sounds" / "sound_library.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("sound_library.json must contain a JSON object")
    return data


def _is_generated(sound: dict[str, Any]) -> bool:
    return sound.get("source_type") == "generated" or sound.get("availability") == "install_generated"


def _display(value: Any, fallback: str = "Not recorded") -> str:
    text = str(value or "").strip()
    return text or fallback


def write_audio_docs(root: Path) -> None:
    data = _manifest(root)
    sounds = [s for s in data.get("sounds", []) if isinstance(s, dict)]
    excluded = [s for s in data.get("excluded_sounds", []) if isinstance(s, dict)]
    generated = [s for s in sounds if _is_generated(s)]
    curated = [s for s in sounds if not _is_generated(s)]

    credits = [
        "# Audio credits\n\n",
        "Nocturne's public catalog contains bundled recorded ambience and procedural beds generated locally during install. "
        "CC0 does not require attribution, but Nocturne records creators and sources anyway. Excluded evidence is listed separately and is not playable through the public catalog.\n\n",
        "## Generated locally by Nocturne\n\n",
    ]
    for sound in generated:
        label = "experimental" if sound.get("status") == "experimental" else "optional"
        credits.append(
            f"- **{_display(sound.get('name'), _display(sound.get('id')))}** — `{_display(sound.get('src'))}`; "
            f"generated by `scripts/generate_noise.py`; {label}; created during install, not shipped as a WAV in the source archive.\n"
        )

    credits.append("\n## Bundled recorded ambience\n\n")
    for sound in curated:
        default_note = "; Tonight default" if sound.get("recommended") else "; optional"
        credits.append(
            f"- **{_display(sound.get('name'), _display(sound.get('id')))}** — "
            f"{_display(sound.get('creator'))}; {_display(sound.get('license'))}; "
            f"{_display(sound.get('source_url'))}{default_note}.\n"
        )

    credits.append("\n## Excluded or quarantined evidence\n\n")
    for item in excluded:
        path = item.get("quarantine_path")
        if item.get("retention") == "evidence_bundle" and path:
            location = f"companion evidence bundle (`{path}`)"
        else:
            location = f"`{path}`" if path else "payload not shipped"
        reason = _display(item.get("reason"), "excluded pending review").rstrip(".")
        credits.append(
            f"- **{_display(item.get('name'), _display(item.get('id')))}** — {location}; "
            f"not public; {reason}.\n"
        )

    provenance = [
        "# Audio provenance\n\n",
        "This is the audit trail for public catalog sounds and retained exclusion evidence. A public recorded sound should have a source URL, creator, license, verification/download date, source screenshot, processed-file hash, and an honest edit description. Generated beds are install-time outputs and therefore do not have a single packaged WAV hash.\n",
    ]

    for sound in sounds:
        is_generated = _is_generated(sound)
        provenance.extend(
            [
                f"\n## {_display(sound.get('name'), _display(sound.get('id')))}\n",
                f"- App ID: `{_display(sound.get('id'))}`\n",
                f"- Public file: `{_display(sound.get('src'))}`\n",
                f"- Status / availability: `{_display(sound.get('status'))}` / `{_display(sound.get('availability'))}`\n",
                f"- Tonight default: `{'yes' if sound.get('recommended') else 'no'}`\n",
                f"- Category / theme: `{_display(sound.get('category'))}` / `{_display(sound.get('theme'))}`\n",
                f"- Source: {_display(sound.get('source'), 'Generated by Nocturne' if is_generated else 'Not recorded')}\n",
                f"- Original title: {_display(sound.get('source_title'), 'Not applicable — procedural synthesis' if is_generated else 'Not recorded')}\n",
                f"- Creator: {_display(sound.get('creator'), 'Nocturne generate_noise.py' if is_generated else 'Not recorded')}\n",
                f"- URL: {_display(sound.get('source_url'), 'Not applicable — generated locally' if is_generated else 'Not recorded')}\n",
                f"- License: {_display(sound.get('license'), _display(sound.get('license_note')))}\n",
                f"- Downloaded / generated: {_display(sound.get('downloaded_at'), 'Generated during local install' if is_generated else 'Not recorded')}\n",
                f"- Screenshot: {_display(sound.get('screenshot'), 'Not applicable — procedural synthesis' if is_generated else 'Not recorded')}\n",
                f"- SHA-256: `{_display(sound.get('sha256'), 'per-install output; no packaged WAV hash' if is_generated else 'Not recorded')}`\n",
                f"- Edits: {_display(sound.get('edits'), 'Procedural synthesis with conservative level limiting and tail/head loop blending' if is_generated else 'Not recorded')}\n",
                f"- Notes: {_display(sound.get('notes'), _display(sound.get('description'), 'None recorded'))}\n",
            ]
        )

    provenance.append("\n# Excluded or quarantined evidence\n")
    for item in excluded:
        provenance.extend(
            [
                f"\n## {_display(item.get('name'), _display(item.get('id')))}\n",
                f"- App ID: `{_display(item.get('id'))}`\n",
                "- Public: `no`\n",
                f"- Status: `{_display(item.get('status'), 'quarantined')}`\n",
                f"- Retention: `{_display(item.get('retention'), 'metadata only / package-local when present')}`\n",
                f"- Quarantine path: `{_display(item.get('quarantine_path'), 'payload not shipped')}`\n",
                f"- Transform sidecar: `{_display(item.get('transform_sidecar'), 'not applicable')}`\n",
                f"- Transform sidecar SHA-256: `{_display(item.get('transform_sidecar_sha256'), 'not applicable')}`\n",
                f"- Reason: {_display(item.get('reason'))}\n",
                f"- Source: {_display(item.get('source_url'))}\n",
                f"- Creator: {_display(item.get('creator'))}\n",
                f"- License: {_display(item.get('license'))}\n",
                f"- Retained SHA-256: `{_display(item.get('sha256'))}`\n",
                f"- Screenshot: {_display(item.get('screenshot'))}\n",
            ]
        )

    (root / "AUDIO_CREDITS.md").write_text("".join(credits), encoding="utf-8")
    (root / "AUDIO_PROVENANCE.md").write_text("".join(provenance), encoding="utf-8")
    print("Wrote AUDIO_CREDITS.md and AUDIO_PROVENANCE.md")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    write_audio_docs(args.root.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
