#!/usr/bin/env python3
"""Generate AUDIO_CREDITS.md and AUDIO_PROVENANCE.md from sounds/sound_library.json."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _sounds(root: Path) -> list[dict[str, Any]]:
    path = root / "sounds" / "sound_library.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    return [s for s in data.get("sounds", []) if isinstance(s, dict)]


def _is_generated(sound: dict[str, Any]) -> bool:
    return (
        sound.get("source_type") == "generated"
        or "generate_noise.py" in str(sound.get("license_note", ""))
        or (
            str(sound.get("src", "")).startswith("/sounds/")
            and not str(sound.get("src", "")).startswith("/sounds/library/")
        )
    )


def write_audio_docs(root: Path) -> None:
    sounds = _sounds(root)
    credits = [
        "# Audio Credits\n",
        "Nocturne ships with generated procedural beds and may include curated CC0/user-owned ambience loops. CC0 does not require attribution, but Nocturne credits sources anyway.\n",
        "## Generated by Nocturne\n",
    ]
    generated = [s for s in sounds if _is_generated(s)]
    curated = [s for s in sounds if s not in generated]
    for s in generated:
        credits.append(f"- **{s.get('name', s.get('id'))}** — `{s.get('src','')}`; generated locally by `scripts/generate_noise.py`.\n")
    credits.append("\n## Curated / user-provided sounds\n")
    for s in curated:
        name = s.get("name") or s.get("id")
        creator = s.get("creator") or "TODO creator"
        license_name = s.get("license") or s.get("license_note") or "TODO license"
        url = s.get("source_url") or "TODO source URL"
        credits.append(f"- **{name}** — {creator}; {license_name}; {url}\n")

    provenance = [
        "# Audio Provenance\n",
        "Use this file as the audit trail for every bundled sound. Before public release, every non-generated sound should have a source URL, creator, license, download date, screenshot, and SHA-256 hash.\n",
    ]
    for s in sounds:
        provenance.extend([
            f"\n## {s.get('name') or s.get('id')}\n",
            f"- App ID: `{s.get('id','')}`\n",
            f"- File: `{s.get('src','')}`\n",
            f"- Category/theme: `{s.get('category','')}` / `{s.get('theme','')}`\n",
            f"- Source: {s.get('source','Generated by Nocturne' if _is_generated(s) else 'TODO')}\n",
            f"- Original title: {s.get('source_title', 'Not applicable - procedural synthesis' if _is_generated(s) else 'TODO')}\n",
            f"- Creator: {s.get('creator', 'Nocturne generate_noise.py' if _is_generated(s) else 'TODO')}\n",
            f"- URL: {s.get('source_url', 'Not applicable - generated locally' if _is_generated(s) else 'TODO')}\n",
            f"- License: {s.get('license', s.get('license_note','TODO'))}\n",
            f"- Downloaded/generated: {s.get('downloaded_at','Generated during local install by scripts/generate_noise.py' if _is_generated(s) else 'TODO')}\n",
            f"- Screenshot: {s.get('screenshot','Not applicable - procedural synthesis' if _is_generated(s) else 'TODO')}\n",
            f"- SHA256: `{s.get('sha256','Generated per install; hash depends on generated local file')}`\n",
            f"- Edits: {s.get('edits','Generated, normalized, and loop-crossfaded by scripts/generate_noise.py' if _is_generated(s) else 'TODO')}\n",
            f"- Notes: {s.get('notes', s.get('description',''))}\n",
        ])

    (root / "AUDIO_CREDITS.md").write_text("".join(credits), encoding="utf-8")
    (root / "AUDIO_PROVENANCE.md").write_text("".join(provenance), encoding="utf-8")
    print("Wrote AUDIO_CREDITS.md and AUDIO_PROVENANCE.md")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    write_audio_docs(args.root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
